---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap-v2
  labels:
    name: app-configmap-v2
data:
  DB_USER: root
  DB_HOST: nwdb-svc.default.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret-v2

data:
  DB_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy-v2
  labels:
    name: app-v2
    version: v2
  
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels: 
      name: app-pod-v2
  template:
    metadata:
      name: app-pod-v2
      labels:
        name: app-pod-v2
    spec:
      containers:
      - image: stackupiss/northwind-app:v2
        name: app-container-v2
        imagePullPolicy: Always
        env:
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: app-configmap-v2
        - secretRef:
            name: app-secret-v2
        ports:
        - name: app-http-v2
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app-service-v2
  labels:
    name: app-service-v2
    version: v2
spec:
  type: ClusterIP
  selector:
    name: app-pod-v2
  ports:
  - name: http-v2
    port: 80
    targetPort: app-http-v2


