---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap-v1
  namespace: myns
  labels:
    name: app-configmap-v1
data:
  DB_USER: root
  DB_HOST: mydb-svc.myns.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret-v1
  namespace: myns

data:
  DB_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy-v1
  namespace: myns
  labels:
    name: app-v1
    version: "v1"
  
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels: 
      name: app-pod-v1
  template:
    metadata:
      name: app-pod-v1
      labels:
        name: app-pod-v1
    spec:
      containers:
      - image: stackupiss/northwind-app:v1
        name: app-container-v1
        imagePullPolicy: Always
        env:
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: app-configmap-v1
        - secretRef:
            name: app-secret-v1
        ports:
        - name: app-http-v1
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app-service-v1
  namespace: myns
  labels:
    name: app-service-v1
    version: v1
spec:
  type: ClusterIP
  selector:
    name: app-pod-v1
  ports:
  - name: http-v1
    port: 80
    targetPort: app-http-v1


