apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mydb-pvc
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: "dobs.cso.digitalocean.com"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
