---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: myns
  labels:
    name: app-configmap
data:
  DB_USER: root
  DB_HOST: mydb-svc.myns.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: myns

data:
  DB_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: myns
  labels:
    name: app
    version: "v1"
  
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels: 
      name: app-pod
  template:
    metadata:
      name: app-pod
      labels:
        name: app-pod
    spec:
      containers:
      - image: stackupiss/northwind-app:v2
        name: app-container
        imagePullPolicy: Always
        env:
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: app-configmap
        - secretRef:
            name: app-secret
        ports:
        - name: app-http
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: myns
  labels:
    name: app-service
spec:
  type: LoadBalancer
  selector:
    name: app-pod
  ports:
  - name: http
    port: 80
    targetPort: app-http


